{
  "internalError": 1,
  "message": "El usuario no existe en la base de datos"
}